implement Update Reservation function
Fds17-FinalProject/SweetyPie_Backend pull request #13
Opened 2021-02-02 16:06 UTC by limjoonchul

solved #8 
implement Update Reservation function

2021-02-03 02:44 UTC, FoeverNa commented on src/main/java/com/mip/sharebnb/service/ReservationService.java
> +        boolean flag = false;
중복체크 기능을 메소드 분리해주는게 좋지않을까요?

2021-02-03 02:55 UTC, Tezla-Lee reviewed
확인

2021-02-03 02:55 UTC, Tezla-Lee commented on src/main/java/com/mip/sharebnb/service/ReservationService.java
> +        System.out.println("flag >>>>>>>> " + flag);
이미 이전에 예약했던 날짜들까지 bookDates 안에 포함되어 있으니 그 부분을 고려해서 다시 짜야할 것 같은데요.

2021-02-03 02:55 UTC, Tezla-Lee commented on src/main/java/com/mip/sharebnb/service/ReservationService.java
> +        System.out.println("flag >>>>>>>> " + flag);
그리고 왜 체크인 날짜만 비교하는지...

2021-02-03 02:57 UTC, Tezla-Lee reviewed
확인

2021-02-03 02:57 UTC, Tezla-Lee commented on src/test/java/com/mip/sharebnb/service/ReservationServiceTest.java
> +
데이터 넣어주는 코드를 따로 빼서 메소드 하나 따로 만들어 주면 깔끔해질 것 같음

2021-02-03 03:01 UTC, Tezla-Lee requested changes
고쳐주세요

2021-02-04 08:09 UTC, Tezla-Lee approved these changes

2021-02-04 08:18 UTC, merged