예약 수정하기 기능 구현
Fds17-FinalProject/SweetyPie_Backend pull request #29
Opened 2021-02-05 07:59 UTC by limjoonchul

예약 수정하기 기능 구현

2021-02-05 08:05 UTC, FoeverNa approved these changes
고생햇수~

2021-02-05 09:15 UTC, Tezla-Lee requested changes
댓글 보시고 고쳐주세요 ㅎㅎ

2021-02-05 09:15 UTC, Tezla-Lee commented on src/main/java/com/mip/sharebnb/repository/dynamic/DynamicReservationRepository.java
> +        }
checkout 포함 안하도록 바꿔주세요
goe, before 사용

2021-02-05 09:15 UTC, Tezla-Lee commented on src/main/java/com/mip/sharebnb/repository/dynamic/DynamicReservationRepository.java
> +        }
그리고 기존에 자신이 예약했던 날짜들은 겹쳐도 통과되도록 하는 로직을 추가해야함.
또한, 원래 예약했던 날짜들은 삭제해야함.

-> find 하기전에 원래 날짜들을 삭제한 후 검색하고, 예약변경 가능하면 변경 날짜를 추가하고,
불가능하면 삭제했던 원래 날짜들을 다시 저장하면 될 듯...?

2021-02-05 16:21 UTC, Tezla-Lee requested changes
휘휴 죄송합니다

2021-02-05 16:21 UTC, Tezla-Lee commented on src/main/java/com/mip/sharebnb/repository/dynamic/DynamicReservationRepository.java
> +        }
reservationId 가 다른 것도 다 가져와야 됨. 수정

2021-02-05 16:21 UTC, Tezla-Lee commented on src/main/java/com/mip/sharebnb/service/ReservationService.java
> +        Optional<Reservation> findReservation = Optional.of(reservationRepository.findById(reservationId).orElse(new Reservation()));
id 로 예약을 못 찾으면 에러를 던져주거나 뭔가 조치를 취해야 할 것 같음... 다음 로직을 거칠 필요가 없어보임

2021-02-06 01:08 UTC, Tezla-Lee approved these changes

2021-02-06 01:09 UTC, merged