예약하기 기능 구현
Fds17-FinalProject/SweetyPie_Backend pull request #37
Opened 2021-02-06 05:39 UTC by limjoonchul

예약하기 기능 구현

solved: #16

2021-02-06 06:17 UTC, Tezla-Lee requested changes
ㅎㅎ

2021-02-06 06:17 UTC, Tezla-Lee commented on src/main/java/com/mip/sharebnb/service/ReservationService.java
> +        Member member = optionalMember.get();
멤버를 못 찾아오면 빈 객체 만들어 주지 말고, 에러 처리해야할 듯. 어제도 비슷한 부분 있었음

2021-02-06 06:17 UTC, Tezla-Lee commented on src/main/java/com/mip/sharebnb/service/ReservationService.java
> +        }
여기서 바로 saveBookedDate 하면 예약이 불가능해도 DB에 저장이 됨. 여기선 리스트에만 넣어주어야 함.

2021-02-06 06:17 UTC, Tezla-Lee commented on src/main/java/com/mip/sharebnb/service/ReservationService.java
> +        return sb.toString();
이런식이면 너무 예약코드가 중복되는 경우가 많을 것 같은데......

2021-02-06 06:17 UTC, Tezla-Lee commented on src/test/java/com/mip/sharebnb/controller/ReservationControllerTest.java
> +//                .andExpect(jsonPath("$.totalPrice").value(30000))
http 로 확인 ㄱㄱ

2021-02-06 06:17 UTC, Tezla-Lee commented on src/test/java/com/mip/sharebnb/controller/ReservationControllerTest.java
> +//                .andExpect(jsonPath("$.totalPrice").value(30000))
그리고 북데이트에도 저장 같이 잘 되나 확인점

2021-02-07 08:43 UTC, FoeverNa commented on src/main/java/com/mip/sharebnb/service/ReservationService.java
> +        Optional<Member> optionalMember = Optional.of(memberRepository.findById(reservationDto.getMemberId()).orElseThrow(RuntimeException::new));
Custom Exception 띄우면 어떨까요

2021-02-07 08:44 UTC, Tezla-Lee requested changes

2021-02-07 08:44 UTC, Tezla-Lee commented on src/main/java/com/mip/sharebnb/model/Accommodation.java
> +    private Integer bedNum;
얘는 왜 primitive 타입 안쓰셨나요

2021-02-07 08:44 UTC, Tezla-Lee commented on src/main/java/com/mip/sharebnb/service/ReservationService.java
> +        List<BookedDate> reservations = dynamicReservationRepository.findByAccommodationIdAndDate(accommodationId, checkInDate, checkoutDate);
이렇게 하면 안됨 ㅠㅠ

2021-02-07 09:26 UTC, merged